version: '2' # required to adjust maintainability checks

checks:
  file-lines:
    enabled: false
    config:
      threshold: 250
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.

exclude_patterns:
  - .github/
  - .husky/
  - testing/
  - web/solr/
  - web/wwwroot/lib/
  - web/wwwroot/css/
  - web/wwwroot/font/
  - config/
  - db/
  - dist/
  - features/
  - '**/node_modules/'
  - script/
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - Tests/
  - '**/vendor/'
  - '**/*_test.go'
  - '**/*.d.ts'

plugins:
  eslint:
    enabled: true
  scss-lint:
    enabled: true
