exclude:
  Data_Governance_ETL* | venv | .venv | .tox | .vs | docs | node_modules* | package-lock.json | .cache* | ^web/wwwroot/css*

repos:
  # reformat c#
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        entry: sh -c 'dotnet format -wsa'
        language: system
        files: \.*(?:cs|sln)

  # misc file cleanup
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: pretty-format-json
        exclude: package-lock.json
        args: [--autofix]
      - id: check-json
        exclude: package-lock.json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer

  # isort python files
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.1
    hooks:
      - id: isort
        additional_dependencies: [toml]
        files:  \.py$

  # reformat python
  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
      - id: black
        files:  \.py$
  - repo: https://github.com/atlas-bi/pre-commit-hooks
    rev: 0.0.1 # Get the latest from: https://github.com/atlas-bi/pre-commit-hooks/releases
    hooks:
      - id: clean_model_context
