name: demo

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          email: ${{ secrets.HEROKU_EMAIL }}
          dockerfile_name: Dockerfile
          docker_options: --no-cache --build-arg HOST="${{ secrets.SQL_HOST }}" --build-arg PASSWORD="${{ secrets.SQL_PASS }}" --build-arg USER=${{ secrets.SQL_USER }}
